quarkus.devservices.enabled=false

quarkus.datasource.db-kind=db2
quarkus.datasource.username=db2inst1
quarkus.datasource.password=yourpassword

# prod (Docker container) uses container-name hostname
quarkus.datasource.jdbc.url=jdbc:db2://mydb2:50000/libdb

# dev mode (running on host, ./mvnw quarkus:dev) uses localhost instead
%dev.quarkus.datasource.jdbc.url=jdbc:db2://localhost:50000/libdb
# Drop and recreate tables on startup automatically (Dev only)
quarkus.flyway.clean-at-start=false
quarkus.hibernate-orm.database.generation=drop-and-create

# Optional: Automatically seed initial data using import.sql
quarkus.hibernate-orm.sql-load-script=seed.sql
quarkus.hibernate-orm.log.sql=true

quarkus.quinoa.ui-dir=src/main/webui
quarkus.rest-client.google-books-api.url=https://openlibrary.org
quarkus.rest-client.google-books-api.connect-timeout=5000
quarkus.rest-client.google-books-api.read-timeout=5000

quarkus.cache.caffeine."book-covers-cache".expire-after-write=PT5M

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=library-system
# smallrye.jwt.sign.key.location=privateKey.pem