-- books
INSERT INTO book (id, title, author, isavailable) VALUES ('b1', 'Pride and Prejudice', 'Jane Austen', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b2', 'To Kill a Mockingbird', 'Harper Lee', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b3', '1984', 'George Orwell', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b4', 'The Great Gatsby', 'F. Scott Fitzgerald', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b5', 'One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b6', 'Crime and Punishment', 'Fyodor Dostoevsky', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b7', 'The Catcher in the Rye', 'J.D. Salinger', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b8', 'Jane Eyre', 'Charlotte Bronte', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b9', 'Wuthering Heights', 'Emily Bronte', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b10', 'The Hobbit', 'J.R.R. Tolkien', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b11', 'The Lord of the Rings', 'J.R.R. Tolkien', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b12', 'Frankenstein', 'Mary Shelley', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b13', 'Brave New World', 'Aldous Huxley', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b14', 'Fahrenheit 451', 'Ray Bradbury', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b15', 'Moby-Dick', 'Herman Melville', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b16', 'The Odyssey', 'Homer', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b17', 'The Divine Comedy', 'Dante Alighieri', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b18', 'War and Peace', 'Leo Tolstoy', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b19', 'Anna Karenina', 'Leo Tolstoy', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b20', 'The Brothers Karamazov', 'Fyodor Dostoevsky', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b21', 'Les Miserables', 'Victor Hugo', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b22', 'The Count of Monte Cristo', 'Alexandre Dumas', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b23', 'Don Quixote', 'Miguel de Cervantes', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b24', 'Ulysses', 'James Joyce', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b25', 'Lolita', 'Vladimir Nabokov', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b26', 'The Picture of Dorian Gray', 'Oscar Wilde', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b27', 'Dracula', 'Bram Stoker', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b28', 'Catch-22', 'Joseph Heller', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b29', 'The Grapes of Wrath', 'John Steinbeck', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b30', 'Of Mice and Men', 'John Steinbeck', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b31', 'Slaughterhouse-Five', 'Kurt Vonnegut', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b32', 'Beloved', 'Toni Morrison', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b33', 'Invisible Man', 'Ralph Ellison', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b34', 'The Sound and the Fury', 'William Faulkner', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b35', 'The Handmaid''s Tale', 'Margaret Atwood', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b36', 'The Sun Also Rises', 'Ernest Hemingway', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b37', 'The Old Man and the Sea', 'Ernest Hemingway', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b38', 'A Tale of Two Cities', 'Charles Dickens', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b39', 'Great Expectations', 'Charles Dickens', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b40', 'David Copperfield', 'Charles Dickens', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b41', 'The Metamorphosis', 'Franz Kafka', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b42', 'The Trial', 'Franz Kafka', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b43', 'The Stranger', 'Albert Camus', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b44', 'The Plague', 'Albert Camus', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b45', 'Things Fall Apart', 'Chinua Achebe', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b46', 'Midnight''s Children', 'Salman Rushdie', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b47', 'The God of Small Things', 'Arundhati Roy', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b48', 'Life of Pi', 'Yann Martel', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b49', 'The Alchemist', 'Paulo Coelho', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b50', 'Dune', 'Frank Herbert', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b51', 'Foundation', 'Isaac Asimov', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b52', 'Neuromancer', 'William Gibson', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b53', 'Do Androids Dream of Electric Sheep?', 'Philip K. Dick', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b54', 'The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b55', 'Hyperion', 'Dan Simmons', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b56', 'The Left Hand of Darkness', 'Ursula K. Le Guin', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b57', 'Ender''s Game', 'Orson Scott Card', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b58', 'A Game of Thrones', 'George R.R. Martin', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b59', 'The Name of the Wind', 'Patrick Rothfuss', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b60', 'The Way of Kings', 'Brandon Sanderson', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b61', 'Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b62', 'The Lion, the Witch and the Wardrobe', 'C.S. Lewis', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b63', 'Animal Farm', 'George Orwell', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b64', 'Lord of the Flies', 'William Golding', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b65', 'The Color Purple', 'Alice Walker', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b66', 'The Bell Jar', 'Sylvia Plath', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b67', 'Their Eyes Were Watching God', 'Zora Neale Hurston', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b68', 'In Cold Blood', 'Truman Capote', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b69', 'On the Road', 'Jack Kerouac', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b70', 'The Master and Margarita', 'Mikhail Bulgakov', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b71', 'The Shadow of the Wind', 'Carlos Ruiz Zafon', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b72', 'Kite Runner', 'Khaled Hosseini', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b73', 'A Thousand Splendid Suns', 'Khaled Hosseini', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b74', 'The Book Thief', 'Markus Zusak', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b75', 'Life and Fate', 'Vasily Grossman', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b76', 'The Road', 'Cormac McCarthy', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b77', 'Blood Meridian', 'Cormac McCarthy', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b78', 'Never Let Me Go', 'Kazuo Ishiguro', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b79', 'The Remains of the Day', 'Kazuo Ishiguro', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b80', 'Norwegian Wood', 'Haruki Murakami', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b81', 'Kafka on the Shore', 'Haruki Murakami', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b82', 'The Poisonwood Bible', 'Barbara Kingsolver', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b83', 'A Fine Balance', 'Rohinton Mistry', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b84', 'The Secret History', 'Donna Tartt', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b85', 'The Goldfinch', 'Donna Tartt', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b86', 'The Sympathizer', 'Viet Thanh Nguyen', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b87', 'Sapiens', 'Yuval Noah Harari', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b88', 'Educated', 'Tara Westover', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b89', 'Becoming', 'Michelle Obama', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b90', 'Thinking, Fast and Slow', 'Daniel Kahneman', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b91', 'Man''s Search for Meaning', 'Viktor E. Frankl', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b92', 'The Autobiography of Malcolm X', 'Malcolm X & Alex Haley', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b93', 'Silent Spring', 'Rachel Carson', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b94', 'Guns, Germs, and Steel', 'Jared Diamond', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b95', 'The Selfish Gene', 'Richard Dawkins', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b96', 'Cosmos', 'Carl Sagan', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b97', 'A Brief History of Time', 'Stephen Hawking', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b98', 'Project Hail Mary', 'Andy Weir', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b99', 'Piranesi', 'Susanna Clarke', 1);
INSERT INTO book (id, title, author, isavailable) VALUES ('b100', 'Tomorrow, and Tomorrow, and Tomorrow', 'Gabrielle Zevin', 1);INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m1', 'Mehak Hussain', 'mehak.hussain0@mail.com', '03001000000', 1);

UPDATE member SET role = 'ADMIN' WHERE username = 'zehra';

-- -- members 
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m2', 'Hassan Chaudhry', 'hassan.chaudhry1@mail.com', '03001000001', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m3', 'Faisal Qureshi', 'faisal.qureshi2@mail.com', '03001000002', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m4', 'Hira Hussain', 'hira.hussain3@mail.com', '03001000003', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m5', 'Naveed Rehman', 'naveed.rehman4@mail.com', '03001000004', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m6', 'Bilal Shah', 'bilal.shah5@mail.com', '03001000005', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m7', 'Salman Ahmed', 'salman.ahmed6@mail.com', '03001000006', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m8', 'Hassan Malik', 'hassan.malik7@mail.com', '03001000007', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m9', 'Kashif Qureshi', 'kashif.qureshi8@mail.com', '03001000008', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m10', 'Tania Javed', 'tania.javed9@mail.com', '03001000009', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m11', 'Hassan Rehman', 'hassan.rehman10@mail.com', '03001000010', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m12', 'Amna Rehman', 'amna.rehman11@mail.com', '03001000011', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m13', 'Iqra Qureshi', 'iqra.qureshi12@mail.com', '03001000012', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m14', 'Farah Shah', 'farah.shah13@mail.com', '03001000013', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m15', 'Adeel Khan', 'adeel.khan14@mail.com', '03001000014', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m16', 'Rimsha Sheikh', 'rimsha.sheikh15@mail.com', '03001000015', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m17', 'Sidra Abbasi', 'sidra.abbasi16@mail.com', '03001000016', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m18', 'Waqas Chaudhry', 'waqas.chaudhry17@mail.com', '03001000017', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m19', 'Usman Baig', 'usman.baig18@mail.com', '03001000018', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m20', 'Rimsha Butt', 'rimsha.butt19@mail.com', '03001000019', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m21', 'Zainab Malik', 'zainab.malik20@mail.com', '03001000020', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m22', 'Sobia Hussain', 'sobia.hussain21@mail.com', '03001000021', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m23', 'Mahnoor Farooq', 'mahnoor.farooq22@mail.com', '03001000022', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m24', 'Laiba Chaudhry', 'laiba.chaudhry23@mail.com', '03001000023', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m25', 'Sara Awan', 'sara.awan24@mail.com', '03001000024', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m26', 'Nimra Hussain', 'nimra.hussain25@mail.com', '03001000025', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m27', 'Sobia Malik', 'sobia.malik26@mail.com', '03001000026', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m28', 'Rizwan Iqbal', 'rizwan.iqbal27@mail.com', '03001000027', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m29', 'Mehak Javed', 'mehak.javed28@mail.com', '03001000028', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m30', 'Imran Shah', 'imran.shah29@mail.com', '03001000029', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m31', 'Amna Malik', 'amna.malik30@mail.com', '03001000030', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m32', 'Sara Qureshi', 'sara.qureshi31@mail.com', '03001000031', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m33', 'Haris Iqbal', 'haris.iqbal32@mail.com', '03001000032', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m34', 'Bilal Qureshi', 'bilal.qureshi33@mail.com', '03001000033', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m35', 'Zainab Siddiqui', 'zainab.siddiqui34@mail.com', '03001000034', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m36', 'Adeel Awan', 'adeel.awan35@mail.com', '03001000035', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m37', 'Mehak Farooq', 'mehak.farooq36@mail.com', '03001000036', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m38', 'Mariam Farooq', 'mariam.farooq37@mail.com', '03001000037', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m39', 'Mahnoor Baig', 'mahnoor.baig38@mail.com', '03001000038', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m40', 'Areeba Chaudhry', 'areeba.chaudhry39@mail.com', '03001000039', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m41', 'Sidra Malik', 'sidra.malik40@mail.com', '03001000040', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m42', 'Laiba Sheikh', 'laiba.sheikh41@mail.com', '03001000041', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m43', 'Nimra Qureshi', 'nimra.qureshi42@mail.com', '03001000042', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m44', 'Mariam Awan', 'mariam.awan43@mail.com', '03001000043', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m45', 'Sobia Chaudhry', 'sobia.chaudhry44@mail.com', '03001000044', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m46', 'Mehak Rehman', 'mehak.rehman45@mail.com', '03001000045', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m47', 'Sana Butt', 'sana.butt46@mail.com', '03001000046', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m48', 'Haris Ahmed', 'haris.ahmed47@mail.com', '03001000047', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m49', 'Sana Ahmed', 'sana.ahmed48@mail.com', '03001000048', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m50', 'Sadia Siddiqui', 'sadia.siddiqui49@mail.com', '03001000049', 1);
-- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m51', 'Adeel Malik', 'adeel.malik50@mail.com', '03001000050', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m52', 'Kashif Shah', 'kashif.shah51@mail.com', '03001000051', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m53', 'Adnan Butt', 'adnan.butt52@mail.com', '03001000052', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m54', 'Kashif Gill', 'kashif.gill53@mail.com', '03001000053', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m55', 'Junaid Awan', 'junaid.awan54@mail.com', '03001000054', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m56', 'Usman Chaudhry', 'usman.chaudhry55@mail.com', '03001000055', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m57', 'Hira Qureshi', 'hira.qureshi56@mail.com', '03001000056', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m58', 'Waleed Rehman', 'waleed.rehman57@mail.com', '03001000057', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m59', 'Nimra Chaudhry', 'nimra.chaudhry58@mail.com', '03001000058', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m60', 'Waleed Shah', 'waleed.shah59@mail.com', '03001000059', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m61', 'Salman Shah', 'salman.shah60@mail.com', '03001000060', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m62', 'Junaid Farooq', 'junaid.farooq61@mail.com', '03001000061', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m63', 'Sana Raza', 'sana.raza62@mail.com', '03001000062', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m64', 'Tania Gill', 'tania.gill63@mail.com', '03001000063', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m65', 'Bilal Ahmed', 'bilal.ahmed64@mail.com', '03001000064', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m66', 'Omar Raza', 'omar.raza65@mail.com', '03001000065', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m67', 'Mehak Sheikh', 'mehak.sheikh66@mail.com', '03001000066', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m68', 'Naveed Abbasi', 'naveed.abbasi67@mail.com', '03001000067', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m69', 'Laiba Malik', 'laiba.malik68@mail.com', '03001000068', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m70', 'Sobia Siddiqui', 'sobia.siddiqui69@mail.com', '03001000069', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m71', 'Laiba Awan', 'laiba.awan70@mail.com', '03001000070', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m72', 'Shahzad Chaudhry', 'shahzad.chaudhry71@mail.com', '03001000071', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m73', 'Rizwan Khan', 'rizwan.khan72@mail.com', '03001000072', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m74', 'Naveed Hussain', 'naveed.hussain73@mail.com', '03001000073', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m75', 'Rimsha Chaudhry', 'rimsha.chaudhry74@mail.com', '03001000074', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m76', 'Haris Butt', 'haris.butt75@mail.com', '03001000075', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m77', 'Omar Iqbal', 'omar.iqbal76@mail.com', '03001000076', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m78', 'Salman Sheikh', 'salman.sheikh77@mail.com', '03001000077', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m79', 'Nasir Khan', 'nasir.khan78@mail.com', '03001000078', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m80', 'Komal Chaudhry', 'komal.chaudhry79@mail.com', '03001000079', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m81', 'Tania Sheikh', 'tania.sheikh80@mail.com', '03001000080', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m82', 'Tania Hussain', 'tania.hussain81@mail.com', '03001000081', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m83', 'Mehak Iqbal', 'mehak.iqbal82@mail.com', '03001000082', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m84', 'Mehak Mirza', 'mehak.mirza83@mail.com', '03001000083', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m85', 'Laiba Baig', 'laiba.baig84@mail.com', '03001000084', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m86', 'Usman Farooq', 'usman.farooq85@mail.com', '03001000085', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m87', 'Nimra Mirza', 'nimra.mirza86@mail.com', '03001000086', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m88', 'Ayesha Javed', 'ayesha.javed87@mail.com', '03001000087', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m89', 'Sadia Gill', 'sadia.gill88@mail.com', '03001000088', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m90', 'Hassan Hussain', 'hassan.hussain89@mail.com', '03001000089', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m91', 'Imran Iqbal', 'imran.iqbal90@mail.com', '03001000090', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m92', 'Faisal Ahmed', 'faisal.ahmed91@mail.com', '03001000091', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m93', 'Faisal Shah', 'faisal.shah92@mail.com', '03001000092', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m94', 'Bilal Malik', 'bilal.malik93@mail.com', '03001000093', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m95', 'Komal Gill', 'komal.gill94@mail.com', '03001000094', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m96', 'Fatima Rehman', 'fatima.rehman95@mail.com', '03001000095', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m97', 'Haris Raza', 'haris.raza96@mail.com', '03001000096', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m98', 'Hira Gill', 'hira.gill97@mail.com', '03001000097', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m99', 'Rizwan Sheikh', 'rizwan.sheikh98@mail.com', '03001000098', 1);
-- -- INSERT INTO member (id, name, email, phonenumber, isactive) VALUES ('m100', 'Nida Mirza', 'nida.mirza99@mail.com', '03001000099', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l1', 'b1', 'm1', '2026-02-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l2', 'b2', 'm2', '2026-03-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l3', 'b3', 'm3', '2026-04-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l4', 'b4', 'm4', '2026-05-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l5', 'b5', 'm5', '2026-06-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l6', 'b6', 'm6', '2026-07-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l7', 'b7', 'm7', '2026-08-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l8', 'b8', 'm8', '2026-09-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l9', 'b9', 'm9', '2026-01-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l10', 'b10', 'm10', '2026-02-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l11', 'b11', 'm11', '2026-03-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l12', 'b12', 'm12', '2026-04-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l13', 'b13', 'm13', '2026-05-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l14', 'b14', 'm14', '2026-06-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l15', 'b15', 'm15', '2026-07-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l16', 'b16', 'm16', '2026-08-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l17', 'b17', 'm17', '2026-09-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l18', 'b18', 'm18', '2026-01-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l19', 'b19', 'm19', '2026-02-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l20', 'b20', 'm20', '2026-03-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l21', 'b21', 'm21', '2026-04-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l22', 'b22', 'm22', '2026-05-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l23', 'b23', 'm23', '2026-06-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l24', 'b24', 'm24', '2026-07-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l25', 'b25', 'm25', '2026-08-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l26', 'b26', 'm26', '2026-09-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l27', 'b27', 'm27', '2026-01-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l28', 'b28', 'm28', '2026-02-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l29', 'b29', 'm29', '2026-03-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l30', 'b30', 'm30', '2026-04-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l31', 'b31', 'm31', '2026-05-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l32', 'b32', 'm32', '2026-06-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l33', 'b33', 'm33', '2026-07-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l34', 'b34', 'm34', '2026-08-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l35', 'b35', 'm35', '2026-09-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l36', 'b36', 'm36', '2026-01-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l37', 'b37', 'm37', '2026-02-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l38', 'b38', 'm38', '2026-03-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l39', 'b39', 'm39', '2026-04-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l40', 'b40', 'm40', '2026-05-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l41', 'b41', 'm41', '2026-06-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l42', 'b42', 'm42', '2026-07-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l43', 'b43', 'm43', '2026-08-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l44', 'b44', 'm44', '2026-09-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l45', 'b45', 'm45', '2026-01-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l46', 'b46', 'm46', '2026-02-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l47', 'b47', 'm47', '2026-03-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l48', 'b48', 'm48', '2026-04-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l49', 'b49', 'm49', '2026-05-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l50', 'b50', 'm50', '2026-06-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l51', 'b51', 'm51', '2026-07-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l52', 'b52', 'm52', '2026-08-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l53', 'b53', 'm53', '2026-09-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l54', 'b54', 'm54', '2026-01-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l55', 'b55', 'm55', '2026-02-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l56', 'b56', 'm56', '2026-03-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l57', 'b57', 'm57', '2026-04-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l58', 'b58', 'm58', '2026-05-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l59', 'b59', 'm59', '2026-06-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l60', 'b60', 'm60', '2026-07-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l61', 'b61', 'm61', '2026-08-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l62', 'b62', 'm62', '2026-09-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l63', 'b63', 'm63', '2026-01-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l64', 'b64', 'm64', '2026-02-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l65', 'b65', 'm65', '2026-03-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l66', 'b66', 'm66', '2026-04-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l67', 'b67', 'm67', '2026-05-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l68', 'b68', 'm68', '2026-06-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l69', 'b69', 'm69', '2026-07-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l70', 'b70', 'm70', '2026-08-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l71', 'b71', 'm71', '2026-09-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l72', 'b72', 'm72', '2026-01-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l73', 'b73', 'm73', '2026-02-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l74', 'b74', 'm74', '2026-03-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l75', 'b75', 'm75', '2026-04-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l76', 'b76', 'm76', '2026-05-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l77', 'b77', 'm77', '2026-06-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l78', 'b78', 'm78', '2026-07-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l79', 'b79', 'm79', '2026-08-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l80', 'b80', 'm80', '2026-09-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l81', 'b81', 'm81', '2026-01-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l82', 'b82', 'm82', '2026-02-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l83', 'b83', 'm83', '2026-03-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l84', 'b84', 'm84', '2026-04-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l85', 'b85', 'm85', '2026-05-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l86', 'b86', 'm86', '2026-06-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l87', 'b87', 'm87', '2026-07-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l88', 'b88', 'm88', '2026-08-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l89', 'b89', 'm89', '2026-09-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l90', 'b90', 'm90', '2026-01-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l91', 'b91', 'm91', '2026-02-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l92', 'b92', 'm92', '2026-03-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l93', 'b93', 'm93', '2026-04-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l94', 'b94', 'm94', '2026-05-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l95', 'b95', 'm95', '2026-06-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l96', 'b96', 'm96', '2026-07-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l97', 'b97', 'm97', '2026-08-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l98', 'b98', 'm98', '2026-09-15', 1);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l99', 'b99', 'm99', '2026-01-15', 0);
-- INSERT INTO lending (id, bookid, memberid, lendingdate, isreturned) VALUES ('l100', 'b100', 'm100', '2026-02-15', 1);
